language: bash
sudo: required
dist: trusty

# libssh-dev removed
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libssh-dev ruby-dev rake-compiler
  - sudo apt-get install -y python3-dev python3.4-dev libpython-dev python-dev
  - sudo apt-get --only-upgrade install ruby
  - ruby -v 
  - sudo apt-get install -y python2.7-dev
  - git clone https://github.com/openSUSE/twopence.git
  - cd twopence
  - sudo make
  - sudo make install
  - sudo ldconfig
script:
    - ruby test/setupTesting.rb
    - ruby test/lavBasicTest.rb
